apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: dev
spec:
  rules:
  - host: test1.apps.example.info
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 80
  - host: test2.apps.example.info
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 80
